### ISSUE TITLE
Max 1024 open files allowed, minimum of 40 000 recommended

### ISSUE THREAD

**Issue by meirarmon** [amoswood/puppet-neo4j#11]
Puppet fails to initialize the server with the error:

WARNING: Max 1024 open files allowed, minimum of 40 000 recommended. See the Neo4j manual.
Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xms1024m -Xmx1024m
Starting Neo4j Server...process [1642]... waiting for server to be ready.. Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.

Need to also change these settings upon provisioning?

**Comment by ccampanale** [comment]
I'm running into this as well however the Max files warning is not the issue. You can fix that by reading the steps [here](http://neo4j.com/docs/stable/linux-performance-guide.html#_setting_the_number_of_open_files) in the Neo4j manual.

That being said, I'm not sure what is causing this to fail. As a side note, it says that it fails to start within 120 seconds but personally it fails immediately and doesn't wait anything close to 120 seconds.

Ideas?

**Comment by meirarmon** [comment]
I fixed it by setting more RAM for my machine
