### ISSUE TITLE
Incorrect Project URL on The Forge Site

### ISSUE THREAD

**Issue by chad-thompson** [amoswood/puppet-neo4j#4]
Quick issue:  the URL listed for the project on the forge page (https://forge.puppetlabs.com/amosjwood/neo4j ) is giving a 404.  (The URL listed is "https://forge.puppetlabs.com/amosjwood/(https://forge.puppetlabs.com/amosjwood/amosjwood-neo4j)")

I was able to find the project GitHub page through the "issues" link, however.  :-P

**Comment by amoswood** [comment]
Fixed in 1.1.0 release.
